name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: print working directory
        run: |
          find .  

      - name: check ssh access
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}

      - name: check directory
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'pwd && find . | grep deploy.sh'

      - name: Find and save deploy.sh path
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            DEPLOY_PATH=$(find /home/ubuntu -type f -name deploy.sh -print -quit)
            echo "Found path: $DEPLOY_PATH"
            echo "$DEPLOY_PATH" > /home/ubuntu/deploy_path.txt
          '   

      - name: Execute Deployment Script on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \            
            'BASE_DIR=$(pwd)
             SCRIPT_PATH="$BASE_DIR/src/py-fastapi-homework-5-ec2-deploy-task/commands/deploy.sh
             echo "Running: $SCRIPT_PATH"
             bash "$SCRIPT_PATH"'
